<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RANIA-YASSIN" ignored="4" name="Test" tests="9" failures="3" timestamp="2022-02-19T20:36:45 EET" time="226.439" errors="0">
  <testcase name="signup" time="4.336" classname="tests.SignUpWithValidData"/>
  <testcase name="login" time="2.317" classname="tests.SignUpWithValidData"/>
  <testcase name="checkRegisteredUserData" time="1.394" classname="tests.SignUpWithValidData"/>
  <testcase name="updateProfile" time="1.504" classname="tests.SignUpWithValidData"/>
  <testcase name="logout" time="1.083" classname="tests.SignUpWithValidData"/>
  <testcase name="signupWithEmailAlreadyExist" time="2.957" classname="tests.SignupWithEmailAlreadyExist"/>
  <testcase name="signupWithInvalidFirstAndLastName" time="5.627" classname="tests.SignupWithInvalidFirstAndLastName">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.SignupWithInvalidFirstAndLastName.signupWithInvalidFirstAndLastName(SignupWithInvalidFirstAndLastName.java:45)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- signupWithInvalidFirstAndLastName -->
  <testcase name="signupWithLastNameSameAsFirstName" time="3.469" classname="tests.SignupWithLastNameSameAsFirstName">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.SignupWithLastNameSameAsFirstName.signupWithLastNameSameAsFirstName(SignupWithLastNameSameAsFirstName.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- signupWithLastNameSameAsFirstName -->
  <testcase name="signupWithInvalidPassword" time="4.127" classname="tests.SignupWithInvalidPassword">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at tests.SignupWithInvalidPassword.signupWithInvalidPassword(SignupWithInvalidPassword.java:44)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- signupWithInvalidPassword -->
  <testcase name="@AfterSuite generateReport" time="0.0" classname="tests.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite generateReport -->
  <testcase name="@AfterSuite generateReport" time="0.0" classname="tests.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite generateReport -->
  <testcase name="@AfterSuite generateReport" time="0.0" classname="tests.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite generateReport -->
  <testcase name="@AfterSuite generateReport" time="0.0" classname="tests.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite generateReport -->
</testsuite> <!-- Test -->
